### ISSUE TITLE
Undo scfw?

### ISSUE THREAD

**Issue by ZephaniahNoah** [metroid-maniac/SCFW#18]
Is there a way to go back to the original firmware after testing? I tried flashing the official supercardsd firmware and it said the file was too large.

**Comment by OmDRetro** [comment]
Flash this [OFW firmware](https://gbatemp.net/attachments/ofw-zip.432574/) within SCFW then power cycle your GBA once flashing is complete.

**Comment by OmDRetro** [comment]
Hey @ZephaniahNoah,

If we don't receive a response from you within 5 days, we'll be closing this ticket.

**Comment by ZephaniahNoah** [comment]
That did the trick! Thank you
