### ISSUE TITLE
Issue loading some games

### ISSUE THREAD

**Issue by SomeAbyss-One** [metroid-maniac/SCFW#21]
Most games load though other less so and leave you with only a white screen after patching the game. Any suggestions to try and get the games working?

The games in question are mainly V-Rally 3, Metroid Zero Mission and Doom, which all previously worked in the base firmware.

**Comment by OmDRetro** [comment]
Context of concern is a duplicate of [issue#10](https://github.com/metroid-maniac/SCFW/issues/10)

***

This has also been answered on [the SCFW GBA Temp thread comment # 371](https://gbatemp.net/threads/scfw-custom-firmware-kernel-for-supercard.647238/post-10456249)

***

I'll carry over the instructions mentioned in the thread link attached above to [issue#10](https://github.com/metroid-maniac/SCFW/issues/10).

Closing this bug.
