### ISSUE TITLE
Write patched rom to SD card

### ISSUE THREAD

**Issue by BigBrainAFK** [metroid-maniac/SCFW#24]
SCFW already does the patching when you start a game. it would be nice if the fully patched rom gets written back and overrides the original file so loading it the next time is faster and doesnt need patching anymore.

**Comment by OmDRetro** [comment]
Someone beat you to it by filing [issue#8 / bug#8](https://github.com/metroid-maniac/SCFW/issues/8). 

Since this is a duplicate, I'm closing this feature request.
