### ISSUE TITLE
GB save filename issues

### ISSUE THREAD

**Issue by jinyukyo** [metroid-maniac/SCFW#29]
the last char of the GB save filename is missing

**Comment by OmDRetro** [comment]
Sounds like the filename was truncated due to it being longer than the usual which is expected if the filename is way too long.

Since SFCW version 0.2, `the best practice is to ensure that the ROM filename is at a reasonable length` which is more or less 32 characters much like how most GBA emus(emulators on the GBA) handle ROM files.

- Did the long filename prevent you from loading your save?
    - If yes:
        - How long is the filename of the ROM you're playing? Please indicate the length in total characters
        - How many subdirectories is the ROM in?
            - Nested subdirectories can cause issues
        - Have you tried trimming the filename?
    - Otherwise, it's not an issue

**Comment by jinyukyo** [comment]
![gb](https://github.com/user-attachments/assets/da843400-3f90-4dbd-8517-a7ab0bb39411)
sorry my bad english,gb savefile name is different from gb rom name,but gbc is correct.

**Comment by jinyukyo** [comment]
sorry my bad english,gb savefile name is different from gb rom name,but gbc is correct.
![savename](https://github.com/user-attachments/assets/f5fa78d7-db22-486b-8627-d627a02df699)

**Comment by OmDRetro** [comment]
> sorry my bad english,gb savefile name is different from gb rom name,but gbc is correct. ![savename](https://private-user-images.githubusercontent.com/5707099/382237423-f5fa78d7-db22-486b-8627-d627a02df699.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1Mjc3NTgsIm5iZiI6MTczMDUyNzQ1OCwicGF0aCI6Ii81NzA3MDk5LzM4MjIzNzQyMy1mNWZhNzhkNy1kYjIyLTQ4NmItODYyNy1kNjI3YTAyZGY2OTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDJUMDYwNDE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWMzZjkxN2U4M2MwODRkYzE1N2ZhMTkzOWY2ODUxZmU4Mjk4ZjViOTE4YTc0ZjY1NGYzYzhkZDA5MWYwZjk3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.itAPrJwfzSDW10z3R4XobhTxRMT95TV0roVMbtlLY9o)

Actually, good catch.
This is an oversight on my part, but it is relatively minor as the saves still load for the OG GB games
I'll fix this on my next build

**Comment by OmDRetro** [comment]
Thanks for notifying me about that oversight, @jinyukyo .

Just letting you know that this is fixed and it will be included in the next build. 

I'll be marking this as `resolved` once I push the changes.

![Fixed](https://github.com/user-attachments/assets/3f34861d-c45e-4bbe-815d-74d3aa78396a)

**Comment by OmDRetro** [comment]
This is fixed in commit [d264d14](https://github.com/metroid-maniac/SCFW/commit/d264d14ed1fc06f7042a15d0f6c01bb78378c7e5)
