### ISSUE TITLE
"Could not overclock EWRAM" on GBA SP after soft-reset.

### ISSUE THREAD

**Issue by Janni9009** [metroid-maniac/SCFW#3]
The kernel successfully overclocks EWRAM on coldboot, but fails to do so again when soft-resetting.
SCFW is flashed as firmware, firmware is version 0.4.4, kernel is version 0.5.0, console is a EUR GBA-SP, cart is an SC-µSD (clone).

**Comment by metroid-maniac** [comment]
Hi @Janni9009 
The commit 6e53175 should fix this.
Can you please test this kernel?
[scfw.zip](https://github.com/metroid-maniac/SCFW/files/14823606/scfw.zip)
If you can confirm this bug is fixed, I will make this the next release.

**Comment by coreflake1** [comment]
Had the same error on my end (now that I finally got everything running). 
Tried the new version, now it's always able to overclock EWRAM.

**Comment by Janni9009** [comment]
Can confirm, it's fixed. @metroid-maniac
