### ISSUE TITLE
games wont boot 

### ISSUE THREAD

**Issue by ButterScott101** [metroid-maniac/SCFW#5]
Just flashed the supercard and it was successfull but now it wont launch any games

**Comment by MCabal212** [comment]
Upon testing the issue you reported, I faced the same problem as yours. However, I was able to resolve it by deleting the GBA ROM that was previously converted by the Super Card Software on my PC. Instead, I replaced it with the non-patched/converted GBA ROM that was generated by the software. This step was crucial to ensure that the SCFW worked properly again.

It's worth noting that only the original state of the game ROM that I had was able to work with the SCFW. Therefore, I recommend using the original ROM file to ensure that the software functions correctly.

**Comment by metroid-maniac** [comment]
MCabal212's description is accurate - but you can also turn off the patches SCFW applies in the settings menu. Then, prepatched ROMs should work.

**Comment by ButterScott101** [comment]
ok thanks

**Comment by OmDRetro** [comment]
Closing this bug as the issue was solved by @metroid-maniac via [comment](https://github.com/metroid-maniac/SCFW/issues/5#issuecomment-2076798569).
